version: "3.9"  # optional since v1.27.0
services:
  mongodb:
    image: mongo:5.0
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
    - "27017:27017"